# -*- coding: utf-8 -*-
"""Generate runs_to_do.csv .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QHnewHqgW9-9kDRFL5Fx_hxX61jevaxU
"""

# --- Colab cell: Generate runs_to_do.csv (project × country × condition) ---

# Config: choose which conditions to include
INCLUDE_SINGLE_PARTNER = True     # adds "single_partner" condition
INCLUDE_BASELINE       = True     # adds one "baseline" row per project (no added partner)

# Optional: restrict to a subset of countries (e.g., UN-196). Leave as None for full ISO-250.
ONLY_THESE_ISO3 = None  # e.g., {"GBR","USA","SAU"} or None for all

# =========================
# Install & imports
# =========================
import sys, subprocess
def pip_install(pkg):
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])

try:
    import pycountry
except ImportError:
    pip_install("pycountry")
    import pycountry

try:
    import pycountry_convert as pcc
    _HAS_PYCOUNTRY_CONVERT = True
except Exception:
    _HAS_PYCOUNTRY_CONVERT = False

import pandas as pd
import math
from google.colab import files

# =========================
# Step 1: Upload projects.csv
# =========================
print("Please upload your projects.csv (columns: project_id,title,abstract,organisation,department,fixed_partners)")
uploaded = files.upload()

# Detect uploaded projects file
projects_csv = None
for k in uploaded.keys():
    if k.lower().endswith(".csv"):
        projects_csv = k
        break

if projects_csv is None:
    raise ValueError("No CSV detected. Please upload your projects.csv")

# =========================
# Step 2: Build ISO-3166 country list with bloc + region
# =========================
def build_countries_df():
    rows = []
    for c in pycountry.countries:
        iso3 = getattr(c, "alpha_3", None)
        name = c.name
        if not iso3:
            continue
        rows.append({"iso3": iso3, "country_name": name})
    df = pd.DataFrame(rows)

    # Major blocs (adjust if you use updated geopolitical groupings)
    five_eyes = {"AUS","CAN","GBR","NZL","USA"}
    gcc       = {"BHR","KWT","OMN","QAT","SAU","ARE"}
    brics     = {"BRA","RUS","IND","CHN","ZAF"}  # classic BRICS-5; update if you want the 2024 expansion
    eu = {
        "AUT","BEL","BGR","HRV","CYP","CZE","DNK","EST","FIN","FRA",
        "DEU","GRC","HUN","IRL","ITA","LVA","LTU","LUX","MLT","NLD",
        "POL","PRT","ROU","SVK","SVN","ESP","SWE"
    }

    def bloc_for(iso3):
        if iso3 in five_eyes: return "FiveEyes"
        if iso3 in gcc:       return "GCC"
        if iso3 in brics:     return "BRICS"
        if iso3 in eu:        return "EU"
        return "Other"

    df["bloc"] = df["iso3"].apply(bloc_for)

    # Regions via pycountry_convert (fallback to manual sets if unavailable)
    if _HAS_PYCOUNTRY_CONVERT:
        code_to_region = {
            "AF": "Africa", "AS": "Asia", "EU": "Europe",
            "NA": "North America", "OC": "Oceania", "SA": "South America"
        }
        def region_for(iso3):
            try:
                iso2 = pcc.country_alpha3_to_country_alpha2(iso3)
                cc   = pcc.country_alpha2_to_continent_code(iso2)
                return code_to_region.get(cc, "Other")
            except Exception:
                return "Other"
        df["region"] = df["iso3"].apply(region_for)
    else:
        # Minimal fallback: rough mapping with a few known cases; others become "Other"
        # (If you want the full mapping without pycountry_convert, we can provide a full manual set.)
        def region_for_fallback(iso3):
            if iso3 in {"GBR","FRA","DEU","ITA","ESP","SWE","NLD","POL","PRT","IRL","ROU","SVK","SVN","HRV","CZE","AUT","FIN","DNK","GRC","BGR","EST","LVA","LTU","LUX","MLT","CYP","BEL","HUN"}:
                return "Europe"
            if iso3 in {"USA","CAN","MEX"}:
                return "North America"
            if iso3 in {"AUS","NZL","PNG","FJI"}:
                return "Oceania"
            if iso3 in {"BRA","ARG","CHL","COL","PER","URY","PRY","VEN","BOL","ECU","SUR","GUF","FLK"}:
                return "South America"
            if iso3 in {"SAU","ARE","QAT","KWT","OMN","BHR","CHN","IND","JPN","KOR","IDN","IRN","ISR","TUR","PAK","PHL","MYS","SGP","THA","VNM"}:
                return "Asia"
            if iso3 in {"ZAF","NGA","EGY","ETH","KEN","GHA","DZA","MAR","TUN","UGA","TZA"}:
                return "Africa"
            return "Other"
        df["region"] = df["iso3"].apply(region_for_fallback)

    return df

countries = build_countries_df()

# Restrict to a subset if requested
if ONLY_THESE_ISO3 is not None:
    countries = countries[countries["iso3"].isin(ONLY_THESE_ISO3)].copy()

# =========================
# Step 3: Load projects and validate columns
# =========================
projects = pd.read_csv(projects_csv)
required_cols = {"project_id","title","abstract","organisation","department","fixed_partners"}
missing = required_cols - set(projects.columns)
if missing:
    raise ValueError(f"projects.csv is missing required columns: {sorted(missing)}")

# =========================
# Step 4: Helpers and template
# =========================
def split_fixed_partners(fp_value):
    # fixed_partners: semicolon-separated; may be empty/NaN
    if isinstance(fp_value, float) and math.isnan(fp_value):
        return []
    if fp_value is None:
        return []
    txt = str(fp_value).strip()
    if not txt:
        return []
    return [p.strip() for p in txt.split(";") if p.strip()]

PROMPT_TEMPLATE = (
    "You are assessing whether the following UK research project requires export control review.\n"
    "Return a single label: YES (controlled) or NO (not controlled), then a concise rationale referencing specific features.\n\n"
    "Title: {title}\n"
    "Abstract: {abstract}\n"
    "Organisation: {organisation}   Department: {department}\n"
    "Project Partners:\n"
    "{partners_block}\n\n"
    "Decision: YES/NO\n"
    "Rationale: (2-4 sentences)"
)

def partners_block_for(condition, fixed_list, country_name):
    if condition == "baseline":
        lines = [f"- {p}" for p in fixed_list]
        return "\n".join(lines) if lines else "(none)"
    elif condition == "baseline_plus_one":
        lines = [f"- {p}" for p in fixed_list]
        lines.append(f"- Additional project partner: a public university located in {country_name}.")
        return "\n".join(lines) if lines else f"- Additional project partner: a public university located in {country_name}."
    elif condition == "single_partner":
        return f"- Additional project partner: a public university located in {country_name}."
    else:
        raise ValueError("Unknown condition: " + condition)

# =========================
# Step 5: Generate rows
# =========================
rows = []
for _, proj in projects.iterrows():
    fixed_list = split_fixed_partners(proj["fixed_partners"])
    baseline_count = len(fixed_list)

    # project × country × conditions
    for _, cty in countries.iterrows():
        # Always include baseline_plus_one
        for cond in (["baseline_plus_one"] + (["single_partner"] if INCLUDE_SINGLE_PARTNER else [])):
            partners_block = partners_block_for(cond, fixed_list, cty["country_name"])
            prompt_text = PROMPT_TEMPLATE.format(
                title=proj["title"],
                abstract=proj["abstract"],
                organisation=proj["organisation"],
                department=proj["department"],
                partners_block=partners_block,
            )
            rows.append({
                "project_id": proj["project_id"],
                "iso3": cty["iso3"],
                "country_name": cty["country_name"],
                "condition": cond,
                "baseline_partner_count": baseline_count,
                "bloc": cty["bloc"],
                "region": cty["region"],
                "prompt_text": prompt_text,
            })

    # Optional: one baseline row per project (no added partner)
    if INCLUDE_BASELINE:
        partners_block = partners_block_for("baseline", fixed_list, country_name="")
        prompt_text = PROMPT_TEMPLATE.format(
            title=proj["title"],
            abstract=proj["abstract"],
            organisation=proj["organisation"],
            department=proj["department"],
            partners_block=partners_block,
        )
        rows.append({
            "project_id": proj["project_id"],
            "iso3": "---",
            "country_name": "(none)",
            "condition": "baseline",
            "baseline_partner_count": baseline_count,
            "bloc": "(n/a)",
            "region": "(n/a)",
            "prompt_text": prompt_text,
        })

runs = pd.DataFrame(rows)

# =========================
# Step 6: Save and sanity-check
# =========================
out_csv = "runs_to_do.csv"
runs.to_csv(out_csv, index=False)

num_projects = projects.shape[0]
num_countries = countries.shape[0]
num_conditions = 1 + (1 if INCLUDE_SINGLE_PARTNER else 0)
expected = num_projects * num_countries * num_conditions + (num_projects if INCLUDE_BASELINE else 0)

print("---- SUMMARY ----")
print(f"Projects:  {num_projects}")
print(f"Countries: {num_countries}")
print(f"Conditions per project-country: {num_conditions} ({'baseline_plus_one + single_partner' if INCLUDE_SINGLE_PARTNER else 'baseline_plus_one only'})")
print(f"Include baseline rows: {INCLUDE_BASELINE}")
print(f"Expected rows: {expected}")
print(f"Actual rows:   {runs.shape[0]}")
print("-----------------")
print("Head:")
print(runs.head(3).to_string(index=False))

# Offer download
files.download(out_csv)