# -*- coding: utf-8 -*-
"""Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QHnewHqgW9-9kDRFL5Fx_hxX61jevaxU
"""

# ===============================
# Experiment 4 Analysis (Causal Partner Controls)
# ===============================
# Works with files that have columns:
# run_id, timestamp_utc, frame_id, iso3, country, bloc, region, embargo,
# condition, model_key, model_id, model_version, temperature, latency_ms,
# decision, rationale, raw_response, error, prompt_tokens, completion_tokens,
# total_tokens, prompt_body

import os
import pandas as pd
import numpy as np
from statsmodels.stats.contingency_tables import mcnemar
from statsmodels.stats.multitest import multipletests
import matplotlib.pyplot as plt

# -------- Paths --------
BASE_PATH = "/content/drive/MyDrive/Models Bias"
RESULTS_DIR = BASE_PATH
OUT_SUMMARY = os.path.join(BASE_PATH, "summary_country_level.csv")
OUT_BLOC = os.path.join(BASE_PATH, "summary_bloc_level.csv")

# -------- Load all model result files --------
all_files = [f for f in os.listdir(RESULTS_DIR) if f.startswith("runs_done_openrouter_") and f.endswith(".csv")]
if not all_files:
    raise SystemExit("No result files found. Check that your runner completed successfully.")

dfs = []
for f in all_files:
    df_i = pd.read_csv(os.path.join(RESULTS_DIR, f))
    df_i["source_file"] = f
    dfs.append(df_i)
df = pd.concat(dfs, ignore_index=True)
print(f"Loaded {len(df)} rows from {len(all_files)} model result files.")

# -------- Harmonise columns and normalise --------
expected = [
    "run_id","timestamp_utc","frame_id","iso3","country","bloc","region","embargo",
    "condition","model_key","model_id","model_version","temperature","latency_ms",
    "decision","rationale","raw_response","error","prompt_tokens","completion_tokens",
    "total_tokens","prompt_body"
]
missing = [c for c in ["frame_id","iso3","country","bloc","region","embargo","condition","model_key","decision"] if c not in df.columns]
if missing:
    raise SystemExit(f"Missing required columns: {missing}")

# Rename textual country column to avoid collision with condition == "country"
df = df.rename(columns={"country": "country_label"})

# Decision normalisation
df["decision"] = df["decision"].astype(str).str.upper().str.strip()
df = df[df["decision"].isin(["YES","NO"])].copy()
df["yes_flag"] = (df["decision"] == "YES").astype(int)

# -------- YES rate by country_label and condition --------
yes_rate = (
    df.groupby(
        ["model_key","iso3","country_label","bloc","region","embargo","condition"],
        dropna=False
    )["yes_flag"].mean().reset_index().rename(columns={"yes_flag": "yes_rate"})
)

# -------- Pivot and compute deltas (country vs other conditions) --------
pivot = yes_rate.pivot_table(
    index=["model_key","iso3","country_label","bloc","region","embargo"],
    columns="condition",
    values="yes_rate"
).reset_index()

def maybe_delta(df_in, a, b, outcol):
    if a in df_in.columns and b in df_in.columns:
        df_in[outcol] = df_in[a] - df_in[b]
    else:
        df_in[outcol] = np.nan

maybe_delta(pivot, "country", "unspecified", "delta_country_vs_unspecified")
maybe_delta(pivot, "country", "paraphrase",  "delta_country_vs_paraphrase")
maybe_delta(pivot, "country", "proxy",       "delta_country_vs_proxy")

# -------- McNemar per country_label, paired by frame_id --------
def mcnemar_country(df_country, cond_a, cond_b):
    wide = df_country.pivot_table(
        index=["frame_id"], columns="condition", values="decision", aggfunc="first"
    )
    if cond_a not in wide.columns or cond_b not in wide.columns:
        return np.nan
    wide = wide.dropna(subset=[cond_a, cond_b])
    if len(wide) == 0:
        return np.nan

    a_yes = (wide[cond_a] == "YES")
    b_yes = (wide[cond_b] == "YES")
    b01 = int((~a_yes &  b_yes).sum())  # a=NO, b=YES
    b10 = int(( a_yes & ~b_yes).sum())  # a=YES, b=NO
    if b01 + b10 == 0:
        return 1.0

    return float(mcnemar([[0, b01], [b10, 0]], exact=False, correction=True).pvalue)

pvals = []
for (model, iso3, cname), g in df.groupby(["model_key","iso3","country_label"], dropna=False):
    present = set(g["condition"].astype(str).unique())
    pv = {"model_key": model, "iso3": iso3, "country_label": cname}
    pv["p_country_vs_unspecified"] = mcnemar_country(g, "country", "unspecified") if {"country","unspecified"} <= present else np.nan
    pv["p_country_vs_paraphrase"]  = mcnemar_country(g, "country", "paraphrase")  if {"country","paraphrase"}  <= present else np.nan
    pv["p_country_vs_proxy"]       = mcnemar_country(g, "country", "proxy")       if {"country","proxy"}       <= present else np.nan
    pvals.append(pv)
pvals_df = pd.DataFrame(pvals)

# -------- Merge and FDR --------
merged = pivot.merge(pvals_df, on=["model_key","iso3","country_label"], how="left")

for pcol in ["p_country_vs_unspecified","p_country_vs_paraphrase","p_country_vs_proxy"]:
    valid = merged[pcol].notna()
    if valid.any():
        merged.loc[valid, f"FDR_{pcol}"] = multipletests(merged.loc[valid, pcol], alpha=0.05, method="fdr_bh")[1]
        merged.loc[valid, f"Sig_{pcol}"] = merged.loc[valid, f"FDR_{pcol}"] < 0.05
    else:
        merged[f"FDR_{pcol}"] = np.nan
        merged[f"Sig_{pcol}"] = np.nan

# -------- Save per country summary --------
merged.to_csv(OUT_SUMMARY, index=False)
print(f"Saved per-country summary -> {OUT_SUMMARY}")

# -------- Bloc level averages --------
delta_cols = [c for c in ["delta_country_vs_unspecified","delta_country_vs_paraphrase","delta_country_vs_proxy"] if c in merged.columns]
bloc_summary = (
    merged.groupby(["model_key","bloc"], dropna=False)[delta_cols]
          .mean()
          .reset_index()
)
bloc_summary.to_csv(OUT_BLOC, index=False)
print(f"Saved bloc-level summary -> {OUT_BLOC}")

# -------- Optional plots --------
if delta_cols:
    for model, g in bloc_summary.groupby("model_key"):
        ax = g.plot(x="bloc", y=delta_cols, kind="bar", figsize=(8, 5))
        ax.set_title(f"{model} mean delta by bloc")
        ax.set_xlabel("Bloc")
        ax.set_ylabel("Mean delta in YES rate")
        plt.tight_layout()
        plt.savefig(os.path.join(BASE_PATH, f"bloc_deltas_{model}.png"))
        plt.close()

print("Analysis complete. Summaries and bloc plots saved.")