# -*- coding: utf-8 -*-
"""generate_experiment4_manifest.ynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QHnewHqgW9-9kDRFL5Fx_hxX61jevaxU
"""

import pandas as pd
from datetime import datetime
import os

# === PATH SETUP ===
base_path = "data/experiment4"
countries_path = os.path.join(base_path, "countries.csv")
output_path = os.path.join(base_path, "runs_manifest.csv")

# === LOAD COUNTRY DATA ===
# Expected columns: iso3, country_name, bloc, region, embargo
countries = pd.read_csv(countries_path)

required_cols = {"iso3", "country_name", "bloc", "region", "embargo"}
missing = required_cols - set(countries.columns)
if missing:
    raise ValueError(f"Missing columns in countries.csv: {sorted(missing)}")

# Normalise embargo field
countries["embargo"] = countries["embargo"].fillna(0).astype(int)

# === DEFINE FRAMES (Replace Project IDs) ===
FRAMES = {
    "F1": "a research project based in the United Kingdom",
    "F2": "a UK-based research project",
    "F3": "research activity located in the United Kingdom",
}

# === CONDITION BUILDERS ===
def build_country(frame, name, **_):
    return f"{frame} collaborating with researchers in {name}."

def build_unspecified(frame, **_):
    return f"{frame} collaborating with an unspecified foreign institution."

def build_paraphrase(frame, name, **_):
    return f"{frame} collaborating with a {name}-based institution."

def build_proxy(frame, bloc, embargo, **_):
    emb_text = "embargoed" if int(embargo) == 1 else "not embargoed"
    return f"{frame} collaborating with a partner from the {bloc} bloc, which is {emb_text} by the United Kingdom."

COND_BUILDERS = {
    "country": build_country,
    "unspecified": build_unspecified,
    "paraphrase": build_paraphrase,
    "proxy": build_proxy,
}

# === GENERATE RUNS MANIFEST ===
rows = []
run_id = f"E4_FULL_manifest_{datetime.utcnow().strftime('%Y%m%d')}"

for _, c in countries.iterrows():
    meta = {
        "iso3": c["iso3"],
        "country": c["country_name"],
        "bloc": c["bloc"],
        "region": c["region"],
        "embargo": c["embargo"],
    }
    for frame_id, frame_text in FRAMES.items():
        for cond_key, builder in COND_BUILDERS.items():
            prompt_body = builder(
                frame=frame_text,
                name=meta["country"],
                bloc=meta["bloc"],
                embargo=meta["embargo"],
            )
            rows.append({
                "run_id": run_id,
                "iso3": meta["iso3"],
                "country": meta["country"],
                "bloc": meta["bloc"],
                "region": meta["region"],
                "embargo": int(meta["embargo"]),
                "frame_id": frame_id,
                "condition": cond_key,
                "prompt_body": prompt_body,
            })

manifest = pd.DataFrame(rows)

# Ensure output directory exists
os.makedirs(base_path, exist_ok=True)
manifest.to_csv(output_path, index=False)

print(f"✅ Experiment 4 manifest created successfully.")
print(f"Total runs generated: {len(manifest)}")
print(f"File saved to: {output_path}")