# -*- coding: utf-8 -*-
"""charts and maps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QHnewHqgW9-9kDRFL5Fx_hxX61jevaxU
"""

import os, io, zipfile, requests
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Optional: install geo libs if needed
try:
    import geopandas as gpd
except Exception:
    import sys, subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "geopandas", "pyproj", "shapely", "fiona", "requests", "pillow"])
    import geopandas as gpd

from PIL import Image, ImageDraw, ImageFont

# -------- Config --------
ROOT = "/content/drive/MyDrive/Country-Only"
TEMPERATURE_TAG = "t00"   # change to "t20" to plot robustness
GENERATE_BLOCS = True     # set False to skip bloc figures
GENERATE_MAPS  = True     # set False to skip map figures

BLOC_CSV    = os.path.join(ROOT, f"bloc_yesrate_{TEMPERATURE_TAG}.csv")
COUNTRY_CSV = os.path.join(ROOT, f"country_yesrate_{TEMPERATURE_TAG}.csv")
OUT_DIR     = os.path.join(ROOT, f"figures_countryonly_{TEMPERATURE_TAG}")
os.makedirs(OUT_DIR, exist_ok=True)

# -------- Helpers: Composite builder (2×3 grid) --------
def make_composite(image_paths, title_text, out_path, grid=(2,3), tile_size=(1400,900), pad=16, title_tile=True):
    """
    Combine up to 5 images into a 2x3 grid. The sixth tile is a title panel.
    image_paths: list of file paths (<=5)
    """
    cols = grid[1]; rows = grid[0]
    W, H = tile_size
    canvas = Image.new("RGB", (cols*W + (cols+1)*pad, rows*H + (rows+1)*pad), (255,255,255))

    # Paste up to 5 images
    for idx, pth in enumerate(image_paths[:5]):
        r = idx // cols
        c = idx %  cols
        x = pad + c*(W+pad)
        y = pad + r*(H+pad)
        try:
            im = Image.open(pth).convert("RGB")
            im = im.resize((W, H), Image.LANCZOS)
            canvas.paste(im, (x, y))
        except Exception as e:
            # draw placeholder
            draw = ImageDraw.Draw(canvas)
            draw.rectangle([x, y, x+W, y+H], outline=(0,0,0), width=2)
            draw.text((x+20, y+20), f"Missing:\n{os.path.basename(pth)}", fill=(0,0,0))
    # Sixth tile as title panel
    if title_tile:
        x = pad + (cols-1)*(W+pad)
        y = pad + (rows-1)*(H+pad)
        draw = ImageDraw.Draw(canvas)
        draw.rectangle([x, y, x+W, y+H], fill=(248,248,248), outline=(0,0,0), width=2)
        # try to load a font; fallback to default
        try:
            font = ImageFont.truetype("DejaVuSans-Bold.ttf", 48)
            font2= ImageFont.truetype("DejaVuSans.ttf", 32)
        except:
            font = None
            font2= None
        draw.text((x+40, y+40), title_text, fill=(0,0,0), font=font if font else None)
        draw.text((x+40, y+120), f"{TEMPERATURE_TAG.upper()}  •  {len(image_paths)} models", fill=(40,40,40), font=font2 if font2 else None)

    canvas.save(out_path, quality=95)
    print("Composite saved:", out_path)

# -------- Load data --------
bloc = pd.read_csv(BLOC_CSV) if GENERATE_BLOCS else None
country = pd.read_csv(COUNTRY_CSV) if GENERATE_MAPS else None

# -------- Sanity & ordering --------
if GENERATE_BLOCS:
    need_bloc = {"model_key","bloc","yes_rate","ci_low","ci_high","n"}
    missing = need_bloc - set(bloc.columns)
    if missing: raise SystemExit(f"bloc CSV missing: {sorted(missing)}")
    bloc_order = ["FiveEyes","EU","GCC","BRICS","Other"]
    bloc["bloc"] = pd.Categorical(bloc["bloc"], categories=bloc_order, ordered=True)

if GENERATE_MAPS:
    need_ctry = {"model_key","iso3","country_name","yes_rate","ci_low","ci_high","n"}
    missing = need_ctry - set(country.columns)
    if missing: raise SystemExit(f"country CSV missing: {sorted(missing)}")

# -------- Bloc bar charts (5 + composite) --------
bloc_paths = []
if GENERATE_BLOCS:
    for mk in sorted(bloc["model_key"].unique()):
        sub = (bloc[bloc["model_key"] == mk]
               .dropna(subset=["yes_rate"])
               .sort_values("bloc"))
        x = np.arange(len(sub))
        y = sub["yes_rate"].to_numpy(float)

        # robust CIs
        ci_low_s  = pd.to_numeric(sub["ci_low"],  errors="coerce")
        ci_high_s = pd.to_numeric(sub["ci_high"], errors="coerce")
        y_series  = pd.Series(y, index=sub.index)
        ci_low  = ci_low_s.combine_first(y_series).to_numpy(float)
        ci_high = ci_high_s.combine_first(y_series).to_numpy(float)
        lower_err = np.maximum(0.0, y - ci_low)
        upper_err = np.maximum(0.0, ci_high - y)
        yerr = np.vstack([lower_err, upper_err])

        plt.figure(figsize=(7.0, 4.6), dpi=220)
        plt.bar(x, y)
        plt.errorbar(x, y, yerr=yerr, fmt="none", capsize=3, linewidth=1)
        plt.xticks(x, sub["bloc"].astype(str))
        plt.ylim(0, 1)
        plt.ylabel("YES propensity")
        plt.title(f"Bloc YES propensity ({TEMPERATURE_TAG}): {mk}")
        plt.tight_layout()

        out_path = os.path.join(OUT_DIR, f"bloc_yesrate_{mk}_{TEMPERATURE_TAG}.png")
        plt.savefig(out_path)
        plt.close()
        bloc_paths.append(out_path)
        print("Saved:", out_path)

    # Composite (sixth)
    if len(bloc_paths) >= 1:
        comp_path = os.path.join(OUT_DIR, f"bloc_yesrate_all_{TEMPERATURE_TAG}.png")
        make_composite(bloc_paths, "Bloc YES propensity — all models", comp_path)

# -------- Robust Natural Earth downloader (for maps) --------
def ensure_natural_earth():
    NE_MIRRORS = [
        "https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_countries.zip",
        "https://github.com/nvkelso/natural-earth-vector/releases/download/v5.0.1/ne_110m_admin_0_countries.zip",
        "https://cdn.jsdelivr.net/gh/nvkelso/natural-earth-vector@master/geojson/ne_110m_admin_0_countries.zip",
    ]
    NE_ZIP = os.path.join(OUT_DIR, "ne_110m_admin_0_countries.zip")
    NE_DIR = os.path.join(OUT_DIR, "ne_110m_admin_0_countries")

    if os.path.isdir(NE_DIR):
        for fn in os.listdir(NE_DIR):
            if fn.endswith(".shp"):
                return os.path.join(NE_DIR, fn)

    os.makedirs(NE_DIR, exist_ok=True)
    last_err = None
    headers = {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) ColabPlotter/1.0"}
    for url in NE_MIRRORS:
        try:
            print("Downloading:", url)
            r = requests.get(url, timeout=60, headers=headers)
            r.raise_for_status()
            with zipfile.ZipFile(io.BytesIO(r.content)) as z:
                z.testzip()
                z.extractall(NE_DIR)
            for fn in os.listdir(NE_DIR):
                if fn.endswith(".shp"):
                    return os.path.join(NE_DIR, fn)
        except Exception as e:
            last_err = e
            print("  -> failed, trying next…", e)
    raise SystemExit(f"All Natural Earth mirrors failed. Last error: {last_err}")

# -------- Country maps (5 + composite) --------
map_paths = []
if GENERATE_MAPS:
    shp_path = ensure_natural_earth()
    world = gpd.read_file(shp_path)
    # normalise ISO3
    world["iso3"] = None
    for col in ["ADM0_A3", "ISO_A3", "ADM0_A3_US", "ADM0_A3_UN", "adm0_a3"]:
        if col in world.columns and world["iso3"].isna().all():
            world["iso3"] = world[col]
    world["iso3"] = world["iso3"].astype(str).str.upper().replace({"SDS":"SSD","KOS":"XKX","-99":np.nan})
    world = world.to_crs("EPSG:4326")

    for mk in sorted(country["model_key"].unique()):
        sub = country[country["model_key"] == mk].copy()
        sub = sub.sort_values(["iso3","n"], ascending=[True, False]).drop_duplicates("iso3")

        gdf = world.merge(sub[["iso3","yes_rate"]], on="iso3", how="left")

        plt.figure(figsize=(9.2, 5.6), dpi=220)
        ax = plt.gca()
        gdf.plot(ax=ax, edgecolor="black", linewidth=0.2, color="lightgrey")
        gdf_valid = gdf.dropna(subset=["yes_rate"])
        if not gdf_valid.empty:
            gdf_valid.plot(ax=ax, column="yes_rate", legend=True)
        ax.set_axis_off()
        plt.title(f"Country YES propensity ({TEMPERATURE_TAG}): {mk}")
        plt.tight_layout()

        out_path = os.path.join(OUT_DIR, f"map_yesrate_{mk}_{TEMPERATURE_TAG}.png")
        plt.savefig(out_path, bbox_inches="tight")
        plt.close()
        map_paths.append(out_path)
        print("Saved:", out_path)

    # Composite (sixth)
    if len(map_paths) >= 1:
        comp_map = os.path.join(OUT_DIR, f"map_yesrate_all_{TEMPERATURE_TAG}.png")
        make_composite(map_paths, "Country YES propensity — all models", comp_map)

print("\nAll figures written to:", OUT_DIR)