# -*- coding: utf-8 -*-
"""Country-Only Prior — Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QHnewHqgW9-9kDRFL5Fx_hxX61jevaxU
"""

# ===========================
# Country-Only Prior — Analysis
# ===========================
# - Reads runs_done_openrouter_<model>_tXX.csv for all models
# - Computes YES propensity by country and bloc with Wilson 95% CIs
# - Optional: bloc-vs-bloc two-proportion tests with BH-FDR
# - Writes tidy CSVs for figures and LaTeX
#
#

import os
import math
import pandas as pd
import numpy as np
from google.colab import drive

# -------- Mount Drive --------
drive.mount("/content/drive")

# -------- Config --------
ROOT = "/content/drive/MyDrive/Country-Only"
TEMPERATURE_TAG = "t00"  # change to "t20" if you rerun a robustness subset at T=0.2
MODEL_KEYS = ["chatgpt_4o","claude_sonnet4","gemini2_5","llama3_3","qwen2_5"]

# Optional: run bloc-to-bloc statistics (two-proportion z-test with BH-FDR)
RUN_BLOC_TESTS = True
BLOC_TEST_CONTRASTS = [("BRICS","EU"), ("GCC","EU"), ("BRICS","FiveEyes"), ("GCC","FiveEyes")]

os.makedirs(ROOT, exist_ok=True)

# -------- Helpers --------
def wilson_ci(k, n, z=1.96):
    if n == 0:
        return (np.nan, np.nan)
    p = k / n
    denom = 1 + z*z/n
    centre = (p + z*z/(2*n)) / denom
    half   = (z * math.sqrt((p*(1-p)/n) + (z*z/(4*n*n)))) / denom
    return (centre - half, centre + half)

def load_all_models(root: str, models: list, ttag: str):
    dfs = []
    for mk in models:
        f = os.path.join(root, f"runs_done_openrouter_{mk}_{ttag}.csv")
        if not os.path.exists(f):
            print(f"⚠️  Missing file (skipping): {f}")
            continue
        df = pd.read_csv(f)
        # Ensure model_key column exists/consistent
        if "model_key" not in df.columns:
            df["model_key"] = mk
        else:
            df["model_key"] = df["model_key"].fillna(mk)
        dfs.append(df)
    if not dfs:
        raise SystemExit("No model output files found.")
    allruns = pd.concat(dfs, ignore_index=True)
    # Keep only parsed decisions
    allruns = allruns[allruns["decision"].isin(["YES","NO"])].copy()
    # Binary outcome
    allruns["y"] = (allruns["decision"] == "YES").astype(int)
    return allruns

# -------- Load --------
allruns = load_all_models(ROOT, MODEL_KEYS, TEMPERATURE_TAG)
print("✅ Loaded rows:", len(allruns))
print("Columns:", list(allruns.columns)[:20], "...")

# Sanity checks
needed = {"model_key","iso3","country_name","bloc","region","y"}
missing = needed - set(allruns.columns)
if missing:
    raise SystemExit(f"Missing required columns in outputs: {sorted(missing)}")

# -------- Country-level YES propensities --------
by_country = (allruns
              .groupby(["model_key","iso3","country_name","bloc","region"], as_index=False)
              .agg(n=("y","size"), yes=("y","sum")))
by_country["yes_rate"] = by_country["yes"] / by_country["n"]
by_country[["ci_low","ci_high"]] = by_country.apply(
    lambda r: pd.Series(wilson_ci(r["yes"], r["n"])), axis=1
)

# Save per-country
country_csv = os.path.join(ROOT, f"country_yesrate_{TEMPERATURE_TAG}.csv")
by_country.to_csv(country_csv, index=False)
print("💾 Saved:", country_csv)

# -------- Bloc-level YES propensities --------
by_bloc = (allruns
           .groupby(["model_key","bloc"], as_index=False)
           .agg(n=("y","size"), yes=("y","sum")))
by_bloc["yes_rate"] = by_bloc["yes"] / by_bloc["n"]
by_bloc[["ci_low","ci_high"]] = by_bloc.apply(
    lambda r: pd.Series(wilson_ci(r["yes"], r["n"])), axis=1
)

bloc_csv = os.path.join(ROOT, f"bloc_yesrate_{TEMPERATURE_TAG}.csv")
by_bloc.to_csv(bloc_csv, index=False)
print("💾 Saved:", bloc_csv)

# -------- Optional: bloc-to-bloc contrasts with BH-FDR --------
if RUN_BLOC_TESTS:
    from math import sqrt
    from statsmodels.stats.multitest import multipletests

    rows=[]
    for mk in by_bloc["model_key"].unique():
        sub = by_bloc[by_bloc["model_key"]==mk]
        lookup = sub.set_index("bloc")[["yes","n"]].to_dict(orient="index")
        for a,b in BLOC_TEST_CONTRASTS:
            if a not in lookup or b not in lookup:
                continue
            ya, na = lookup[a]["yes"], lookup[a]["n"]
            yb, nb = lookup[b]["yes"], lookup[b]["n"]
            pa, pb = ya/na, yb/nb
            # Two-proportion z-test (pooled)
            p_pool = (ya+yb)/(na+nb)
            se = sqrt(p_pool*(1-p_pool)*(1/na + 1/nb))
            if se == 0:
                z = np.nan
                p = 1.0
            else:
                z = (pa - pb) / se
                # two-sided p
                from scipy.stats import norm
                p = 2*(1 - norm.cdf(abs(z)))
            rows.append({"model_key": mk, "contrast": f"{a} vs {b}",
                         "pa": pa, "pb": pb, "delta": pa-pb, "z": z, "p": p,
                         "na": na, "nb": nb})

    bloc_tests = pd.DataFrame(rows)
    if len(bloc_tests):
        # BH-FDR by model
        bloc_tests = bloc_tests.sort_values(["model_key","p"])
        bloc_tests["p_adj"] = np.nan
        for mk in bloc_tests["model_key"].unique():
            idx = bloc_tests["model_key"]==mk
            _, p_adj, _, _ = multipletests(bloc_tests.loc[idx,"p"], method="fdr_bh")
            bloc_tests.loc[idx,"p_adj"] = p_adj

        tests_csv = os.path.join(ROOT, f"bloc_contrasts_{TEMPERATURE_TAG}.csv")
        bloc_tests.to_csv(tests_csv, index=False)
        print("💾 Saved:", tests_csv)

# -------- Quick text summary (top/bottom countries per model) --------
def top_bottom(df, k=5):
    rows=[]
    for mk in sorted(df["model_key"].unique()):
        sub = df[df["model_key"]==mk].sort_values("yes_rate", ascending=False)
        rows.append({"model_key": mk, "type": "top", "countries":
                     ", ".join([f"{r.country_name} ({r.yes_rate:.2f})" for _,r in sub.head(k).iterrows()])})
        rows.append({"model_key": mk, "type": "bottom", "countries":
                     ", ".join([f"{r.country_name} ({r.yes_rate:.2f})" for _,r in sub.tail(k).iterrows()])})
    return pd.DataFrame(rows)

tb = top_bottom(by_country, k=5)
tb_csv = os.path.join(ROOT, f"country_yesrate_topbottom_{TEMPERATURE_TAG}.csv")
tb.to_csv(tb_csv, index=False)
print("💾 Saved:", tb_csv)

# -------- Print a concise console view --------
print("\n=== Bloc YES rates (first few) ===")
print(by_bloc.sort_values(["model_key","yes_rate"], ascending=[True,False]).head(15).to_string(index=False))

print("\n=== Example: Top/Bottom countries per model (yes_rate) ===")
print(tb.to_string(index=False))