# -*- coding: utf-8 -*-
"""Country-Only Prior.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QHnewHqgW9-9kDRFL5Fx_hxX61jevaxU
"""

# ===========================
# Experiment 3: Country-Only Prior Test (single-stage)
# ===========================
# - One decision per (project × country)
# - No Stage 1 baseline, no pairing; measures absolute YES propensity by partner country
# - Output CSV is compatible with your existing OpenRouter runner

import os, math, hashlib, re
import pandas as pd
from google.colab import drive

# -------- Mount Drive (no-op if already mounted) --------
drive.mount('/content/drive')

# -------- Paths --------
ROOT_DIR   = "/content/drive/MyDrive/Country-Only"
EXP_DIR    = os.path.join(ROOT_DIR, "CountryOnly_Priors")
os.makedirs(EXP_DIR, exist_ok=True)

PROJECTS_CSV  = os.path.join(ROOT_DIR, "projects.csv")          #
COUNTRIES_CSV = os.path.join(ROOT_DIR, "countries.csv")         # your ISO3 + bloc + region (≈249)
OUT_CSV       = os.path.join(EXP_DIR, "runs_to_do_countryonly.csv")

assert os.path.exists(PROJECTS_CSV),  f"Missing: {PROJECTS_CSV}"
assert os.path.exists(COUNTRIES_CSV), f"Missing: {COUNTRIES_CSV}"

# -------- Load inputs --------
projects  = pd.read_csv(PROJECTS_CSV)
countries = pd.read_csv(COUNTRIES_CSV)

# Ensure minimal columns
need_p = {"project_id"}  # we only need an id per project
need_c = {"iso3","country_name","bloc","region"}
miss_p = need_p - set(projects.columns)
miss_c = need_c - set(countries.columns)
if miss_p: raise ValueError(f"projects.csv missing: {sorted(miss_p)}")
if miss_c: raise ValueError(f"countries.csv missing: {sorted(miss_c)}")

# -------- Prompt template (country-only) --------
PROMPT_TEMPLATE = (
    "You are assessing whether the following UK research activity requires export control review.\n"
    "Return exactly one label: YES (controlled) or NO (not controlled), then a one-sentence rationale.\n"
    "Use only the information provided. Do not assume technical details, end use, end user, or sanctions exposure unless stated.\n\n"
    "Jurisdictional scope: UK/EU dual-use and sanctions (do not cite US-specific regimes).\n\n"
    "Project: A UK-based academic research project (no additional technical details).\n"
    "International partner: a public university located in {country_name}.\n\n"
    "Decision: YES/NO\n"
    "Rationale:"
)

def prompt_hash(text: str) -> str:
    return hashlib.sha1(text.encode("utf-8")).hexdigest()

# -------- Build rows: one per (project × country) --------
rows = []
for _, p in projects.iterrows():
    for _, c in countries.iterrows():
        txt = PROMPT_TEMPLATE.format(country_name=c["country_name"])
        rows.append({
            "run_id": "",  # filled below for reproducibility
            "template_version": "e3-countryonly-v1",
            "stage": "SINGLE",
            "parent_run_id": "",
            "project_id": p["project_id"],
            "iso3": c["iso3"],
            "country_name": c["country_name"],
            "condition": "country_only",
            "baseline_partner_count": 0,
            "bloc": c["bloc"],
            "region": c["region"],
            "partner_type": "a public university",
            "prompt_text": txt,
            "prompt_hash": prompt_hash(txt),
            "prompt_len_chars": len(txt),
            "prompt_len_tokens_est": int(len(txt) / 4),  # rough 4 chars/token heuristic
            "s1_decision_hint": "",
            "s1_rationale_hint": "",
        })

runs = pd.DataFrame(rows)

# Deterministic run_id (audit-friendly): hash of key fields
def make_run_id(row):
    m = hashlib.sha256()
    for k in ("project_id","iso3","condition","prompt_hash"):
        m.update(str(row[k]).encode())
    return m.hexdigest()[:40]

runs["run_id"] = runs.apply(make_run_id, axis=1)

# -------- Save and report --------
runs.to_csv(OUT_CSV, index=False)
print("✅ Country-only run plan saved:", OUT_CSV)
print("Projects:", projects.shape[0], "Countries:", countries.shape[0], "Total rows:", runs.shape[0])
print("Head:")
print(runs.head(3).to_string(index=False))