# -*- coding: utf-8 -*-
"""mcnemar_by_country_countryonly_t00.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QHnewHqgW9-9kDRFL5Fx_hxX61jevaxU
"""

# ===============================================
# Country-only Experiment: per-country significance
# - If paired S1/S2 available: McNemar per country
# - Else: Binomial test vs model's global YES rate
# - FDR correction (BH)
# - Output schema aligned with prior McNemar files
# ===============================================

import os
import numpy as np
import pandas as pd
from pathlib import Path
from statsmodels.stats.contingency_tables import mcnemar
from scipy.stats import binomtest

# -------- Paths --------
ROOT = Path("/content/drive/MyDrive/Country-Only")
COUNTRY_SUMMARY = ROOT / "country_yesrate_t00.csv"   # needs: model_key, iso3, country_name, yes_rate, n
OUT_CSV         = ROOT / "mcnemar_by_country_countryonly_t00.csv"

# Optional: if you *do* have paired outputs for country-only (rare), put them here:
model_files = list(ROOT.glob("runs_done_openrouter_*_t00.csv"))

# -------- Helper: Benjamini–Hochberg FDR --------
def bh_fdr(pvals, by_group=None):
    df = pvals.copy()
    if by_group is None:
        df = df.sort_values("p_raw").reset_index(drop=True)
        m = float(len(df))
        df["p_adj"] = (df["p_raw"] * (df.index + 1) / m).clip(upper=1.0)
        return df
    rows = []
    for g, sub in df.groupby(by_group, as_index=False):
        sub = sub.sort_values("p_raw").reset_index(drop=True)
        m = float(len(sub))
        sub["p_adj"] = (sub["p_raw"] * (sub.index + 1) / m).clip(upper=1.0)
        rows.append(sub)
    return pd.concat(rows, ignore_index=True)

# -------- Case A: Paired data available? (McNemar) --------
def paired_available():
    if not model_files:
        return False
    # Check one file for required columns
    try:
        probe = pd.read_csv(model_files[0], nrows=5)
        need = {"project_id","iso3","country_name","decision"}
        has_min = need.issubset(probe.columns)
        # For country-only, we don't usually have s1_label/label; if present, great.
        return has_min
    except Exception:
        return False

# -------- McNemar path (if paired data exist) --------
def run_mcnemar_country_only():
    dfs = []
    for f in model_files:
        df = pd.read_csv(f)
        mk = f.name.split("runs_done_openrouter_")[1].split("_t00")[0]
        df["model_key"] = mk
        # Normalise decisions
        df = df.dropna(subset=["decision","country_name"])
        df["decision"] = df["decision"].astype(str).str.upper().str.strip()
        df["yes"] = (df["decision"] == "YES").astype(int)
        dfs.append(df)
    data = pd.concat(dfs, ignore_index=True)

    # We need *paired* outcomes within model×country×project.
    # If you have replicates per project–country (e.g., multiple prompts),
    # we can pair arbitrary two passes. Otherwise McNemar is not defined.
    # Here we aggregate flips between any two appearances of the same project–country.
    # If only one row exists per project–country, it contributes nothing.
    def mcnemar_for_group(g):
        # group by project, need >=2 rows to form a pair
        b0p1 = b1p0 = 0
        for _, gg in g.groupby("project_id"):
            if gg.shape[0] < 2:  # cannot pair
                continue
            vals = gg.sort_index()["yes"].tolist()
            # Compare first two appearances
            a, b = vals[0], vals[1]
            if a == 1 and b == 0:
                b1p0 += 1
            elif a == 0 and b == 1:
                b0p1 += 1
        n_discordant = b0p1 + b1p0
        if n_discordant == 0:
            p = 1.0
        else:
            res = mcnemar([[0, b0p1],[b1p0, 0]], exact=False, correction=True)
            p = float(res.pvalue)
        return pd.Series(dict(b0p1=b0p1, b1p0=b1p0, n_discordant=n_discordant, p_raw=p, test="mcnemar"))

    out = (data.groupby(["model_key","iso3","country_name"], as_index=False)
                .apply(mcnemar_for_group)
                .reset_index(drop=True))

    out = bh_fdr(out, by_group="model_key")
    # Align column order with your prior files
    out = out[["model_key","iso3","country_name","b0p1","b1p0","n_discordant","p_raw","p_adj","test"]]
    out.to_csv(OUT_CSV, index=False)
    print(f"✅ Saved (McNemar): {OUT_CSV}")
    return out

# -------- Binomial path (default, recommended here) --------
def run_binomial_vs_global_mean():
    # Load per-country rates and counts
    ctry = pd.read_csv(COUNTRY_SUMMARY)
    need = {"model_key","iso3","country_name","yes_rate","n"}
    missing = need - set(ctry.columns)
    if missing:
        raise SystemExit(f"{COUNTRY_SUMMARY} is missing columns: {sorted(missing)}")

    ctry["yes_rate"] = pd.to_numeric(ctry["yes_rate"], errors="coerce")
    ctry["n"] = pd.to_numeric(ctry["n"], errors="coerce").fillna(0).astype(int)
    # Derive k (YES counts)
    ctry["k_yes"] = (ctry["yes_rate"] * ctry["n"]).round().astype(int)

    # Global model-level mean (exclude countries with n==0)
    glob = (ctry[ctry["n"] > 0]
            .groupby("model_key", as_index=False)
            .apply(lambda g: pd.Series(dict(p_global=(g["k_yes"].sum() / g["n"].sum()))))
            .reset_index(drop=True))

    ctry = ctry.merge(glob, on="model_key", how="left")

    # Two-sided binomial test per model×country against p_global
    rows = []
    for (mk, iso3, cname), g in ctry.groupby(["model_key","iso3","country_name"]):
        n = int(g["n"].iloc[0])
        k = int(g["k_yes"].iloc[0])
        p0 = float(g["p_global"].iloc[0])
        if n == 0 or np.isnan(p0):
            p = np.nan
        else:
            p = binomtest(k=k, n=n, p=p0, alternative="two-sided").pvalue
        rows.append({
            "model_key": mk,
            "iso3": iso3,
            "country_name": cname,
            "b0p1": 0,               # not applicable here
            "b1p0": 0,               # not applicable here
            "n_discordant": 0,       # not applicable here
            "p_raw": p,
            "test": "binomial_vs_global"
        })
    out = pd.DataFrame(rows)
    out = bh_fdr(out, by_group="model_key")
    out = out[["model_key","iso3","country_name","b0p1","b1p0","n_discordant","p_raw","p_adj","test"]]
    out.to_csv(OUT_CSV, index=False)
    print(f"✅ Saved (Binomial vs global mean): {OUT_CSV}")
    return out

# -------- Run --------
if paired_available():
    try:
        res = run_mcnemar_country_only()
    except Exception as e:
        print("Paired (McNemar) path failed, falling back to binomial:", e)
        res = run_binomial_vs_global_mean()
else:
    res = run_binomial_vs_global_mean()

print(res.head(10).to_string(index=False))