# -*- coding: utf-8 -*-
"""OpenRouter SINGLE-STAGE runner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QHnewHqgW9-9kDRFL5Fx_hxX61jevaxU
"""

# ===========================
# OpenRouter SINGLE-STAGE runner (Country-Only Prior Experiment)
# ===========================
# - Runs one stage only (no S1/S2 pairing)
# - Compatible with the same output structure as the two-stage protocol
# - Parallel per model, sequential across models
#
# Before running in Colab:
#   import os; os.environ["OPENROUTER_API_KEY"] = "sk-or-..."
#   Then execute this script.

import os, time, json, re, random, csv, threading, math, requests
import pandas as pd
from datetime import datetime, timezone
from queue import Queue
from concurrent.futures import ThreadPoolExecutor, as_completed
from google.colab import drive

# -------- Mount Drive --------
drive.mount('/content/drive')

# -------- Paths --------
ROOT_DIR  = "/content/drive/MyDrive/Country-Only"
INPUT_CSV = f"{ROOT_DIR}/runs_to_do_countryonly.csv"
OUT_BASE  = f"{ROOT_DIR}/runs_done_openrouter"   # -> runs_done_openrouter_<model>_t00.csv
assert os.path.exists(INPUT_CSV), f"Not found: {INPUT_CSV}"

# -------- Model map (OpenRouter IDs) --------
MODEL_MAP = {
    "chatgpt-4o":      "openai/gpt-4o",
    "claude-sonnet-4": "anthropic/claude-sonnet-4",
    "gemini2.5":       "google/gemini-2.5-pro",
    "llama3.3":        "meta-llama/llama-3.3-70b-instruct",
    "qwen2.5":         "qwen/qwen-2.5-72b-instruct",
}

# -------- Per-model throttles --------
PER_MODEL_LIMITS = {
    "qwen2.5":         {"workers": 4, "rps": 3.0},
    "llama3.3":        {"workers": 4, "rps": 3.0},
    "chatgpt-4o":      {"workers": 6, "rps": 3.0},
    "gemini2.5":       {"workers": 6, "rps": 3.0},
    "claude-sonnet-4": {"workers": 6, "rps": 3.0},
}

# -------- Which models to run --------
MODEL_KEYS = ["claude-sonnet-4"]

# -------- Inference settings --------
TEMPERATURE = 0.0
MAX_TOKENS  = 400
SEED        = 42
PILOT_N     = None           # e.g. 50 for pilot
MAX_WORKERS = 6
MAX_RPS     = 3.0
SLEEP_JITTER_MAX = 0.03

# -------- Resume behaviour --------
RESUME = False  # False => overwrite existing files

# -------- OpenRouter API --------
API_KEY = os.getenv("OPENROUTER_API_KEY", "").strip() or "#####"
if not API_KEY:
    raise SystemExit("No OPENROUTER_API_KEY set. In Colab: os.environ['OPENROUTER_API_KEY'] = 'sk-or-...'")

API_URL      = "https://openrouter.ai/api/v1/chat/completions"
HTTP_REFERER = "https://colab.research.google.com"
X_TITLE      = "ExportControl Bias Experiment 3"

# -------- Load input --------
runs = pd.read_csv(INPUT_CSV)

required_cols = {
    "run_id","project_id","iso3","country_name","condition","prompt_text","stage","parent_run_id"
}
missing = required_cols - set(runs.columns)
if missing:
    raise SystemExit(f"runs_to_do_countryonly.csv is missing columns: {sorted(missing)}")

random.seed(SEED)
runs = runs.sample(frac=1.0, random_state=SEED).reset_index(drop=True)
if PILOT_N is not None:
    runs = runs.head(PILOT_N).copy()

# -------- Helpers --------
def slugify(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", s).strip("_").lower()

YESNO_RE = re.compile(r"\b(YES|NO)\b", re.IGNORECASE)
def parse_decision_and_rationale(text: str):
    if not isinstance(text, str) or not text.strip():
        return None, ""
    m = YESNO_RE.search(text)
    decision = m.group(1).upper() if m else None
    m2 = re.search(r"(?is)\bRationale\s*:\s*(.+)", text)
    if m2:
        rationale = m2.group(1).strip()
    else:
        lines = [ln.strip() for ln in text.splitlines() if ln.strip()]
        rationale = "\n".join(lines[1:]) if len(lines) > 1 else (lines[0] if lines else "")
    return decision, rationale

def ensure_outfile(path):
    if not os.path.exists(path):
        cols = [
            "run_id","timestamp_utc",
            "project_id","iso3","country_name","condition",
            "baseline_partner_count","bloc","region",
            "model_key","model_id","model_version","temperature","latency_ms",
            "decision","rationale","raw_response","error",
            "prompt_tokens","completion_tokens","total_tokens"
        ]
        pd.DataFrame(columns=cols).to_csv(path, index=False)

class SoftRateLimiter:
    def __init__(self, rps):
        self.min_interval = 1.0 / max(rps, 0.001)
        self._lock = threading.Lock()
        self._last = 0.0
    def wait(self):
        with self._lock:
            now = time.time()
            delta = now - self._last
            if delta < self.min_interval:
                time.sleep(self.min_interval - delta)
            self._last = time.time()

def call_openrouter(session: requests.Session, model_id: str, prompt: str, limiter: SoftRateLimiter,
                    temperature: float = TEMPERATURE, max_tokens: int = MAX_TOKENS, seed: int = SEED,
                    max_retries: int = 8, backoff_base: float = 1.4, backoff_cap: float = 60.0):
    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json",
        "HTTP-Referer": HTTP_REFERER,
        "X-Title": X_TITLE,
    }
    payload = {
        "model": model_id,
        "messages": [
            {"role": "system", "content": "You are a careful export-control assistant. Be concise and deterministic."},
            {"role": "user", "content": prompt},
        ],
        "temperature": temperature,
        "max_tokens": max_tokens,
        "seed": seed,
    }

    tries = 0
    while True:
        tries += 1
        limiter.wait()
        if SLEEP_JITTER_MAX > 0:
            time.sleep(random.random() * SLEEP_JITTER_MAX)

        t0 = time.time()
        try:
            resp = session.post(API_URL, headers=headers, data=json.dumps(payload), timeout=(15, 240))
            latency_ms = int((time.time() - t0) * 1000)
        except requests.RequestException as e:
            if tries <= max_retries:
                time.sleep(min(backoff_cap, backoff_base ** tries + random.random()))
                continue
            raise RuntimeError(f"NetworkError after {tries} tries: {e}")

        if resp.status_code == 200:
            data = resp.json()
            try:
                content = data["choices"][0]["message"]["content"]
            except Exception:
                content = json.dumps(data)
            usage = data.get("usage", {}) or {}
            model_version = data.get("model", model_id)
            return {
                "content": content,
                "latency_ms": latency_ms,
                "usage": {
                    "prompt_tokens": usage.get("prompt_tokens"),
                    "completion_tokens": usage.get("completion_tokens"),
                    "total_tokens": usage.get("total_tokens"),
                },
                "model_version": model_version,
            }

        if resp.status_code in (408,429,500,502,503,504) and tries <= max_retries:
            retry_after = resp.headers.get("Retry-After")
            sleep_s = float(retry_after) if retry_after else min(backoff_cap, backoff_base ** tries + random.random())
            time.sleep(sleep_s)
            continue

        snippet = resp.text[:400]
        raise RuntimeError(f"HTTP {resp.status_code} (tries={tries}): {snippet}")

def run_rows_for_model(model_key: str, model_id: str, rows_df: pd.DataFrame, out_csv: str):
    limits = PER_MODEL_LIMITS.get(model_key, {})
    local_workers = limits.get("workers", MAX_WORKERS)
    local_rps     = limits.get("rps", MAX_RPS)
    limiter = SoftRateLimiter(local_rps)

    writer_q: Queue = Queue(maxsize=1000)
    writer_stop = object()
    def writer():
        with open(out_csv, "a", newline="", encoding="utf-8") as f:
            fieldnames = [
                "run_id","timestamp_utc",
                "project_id","iso3","country_name","condition",
                "baseline_partner_count","bloc","region",
                "model_key","model_id","model_version","temperature","latency_ms",
                "decision","rationale","raw_response","error",
                "prompt_tokens","completion_tokens","total_tokens"
            ]
            w = csv.DictWriter(f, fieldnames=fieldnames)
            while True:
                item = writer_q.get()
                if item is writer_stop:
                    break
                w.writerow(item)
                f.flush()
                writer_q.task_done()
    wt = threading.Thread(target=writer, daemon=True)
    wt.start()

    session = requests.Session()

    def worker(row_dict):
        prompt = row_dict["prompt_text"]
        error = ""
        decision = rationale = None
        raw = ""
        latency_ms = None
        usage = {"prompt_tokens": None, "completion_tokens": None, "total_tokens": None}
        model_version = model_id

        try:
            resp = call_openrouter(session, model_id, prompt, limiter)
            raw = resp["content"]
            latency_ms = resp["latency_ms"]
            usage = resp["usage"]
            model_version = resp["model_version"]
            decision, rationale = parse_decision_and_rationale(raw)
            if decision not in {"YES","NO"}:
                error = "ParseError: decision not found"
        except Exception as e:
            error = f"{type(e).__name__}: {e}"

        out_row = {
            "run_id": row_dict["run_id"],
            "timestamp_utc": datetime.now(timezone.utc).isoformat(),
            "project_id": row_dict["project_id"],
            "iso3": row_dict["iso3"],
            "country_name": row_dict["country_name"],
            "condition": row_dict["condition"],
            "baseline_partner_count": row_dict.get("baseline_partner_count"),
            "bloc": row_dict.get("bloc"),
            "region": row_dict.get("region"),
            "model_key": model_key,
            "model_id": model_id,
            "model_version": model_version,
            "temperature": TEMPERATURE,
            "latency_ms": latency_ms,
            "decision": decision,
            "rationale": rationale,
            "raw_response": raw,
            "error": error,
            "prompt_tokens": usage.get("prompt_tokens"),
            "completion_tokens": usage.get("completion_tokens"),
            "total_tokens": usage.get("total_tokens"),
        }
        writer_q.put(out_row)

    rows_iter = (rows_df.iloc[i].to_dict() for i in range(len(rows_df)))
    with ThreadPoolExecutor(max_workers=local_workers) as ex:
        futures = [ex.submit(worker, row_dict) for row_dict in rows_iter]
        done = 0
        for fut in as_completed(futures):
            done += 1
            if done % 100 == 0:
                print(f"{model_key}: {done}/{len(futures)} completed...")

    writer_q.put(writer_stop)
    wt.join()

def run_model_single_stage(model_key: str, model_id: str):
    out_csv = f"{OUT_BASE}_{slugify(model_key)}_t{int(TEMPERATURE*100):02d}.csv"
    if not RESUME and os.path.exists(out_csv):
        os.remove(out_csv)
    ensure_outfile(out_csv)

    # Single-stage experiment (no S2)
    print(f"\n=== {model_key} -> {model_id} ===")
    print(f"Total rows: {len(runs)}")
    run_rows_for_model(model_key, model_id, runs, out_csv)
    print(f"Saved -> {out_csv}")

# -------- Run all selected models --------
for key in MODEL_KEYS:
    if key not in MODEL_MAP:
        raise ValueError(f"Unknown model key: {key}")
    run_model_single_stage(key, MODEL_MAP[key])

print("All models completed.")