# -*- coding: utf-8 -*-
"""Generate runs_to_do.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QHnewHqgW9-9kDRFL5Fx_hxX61jevaxU
"""

# --- Colab cell: Generate runs_to_do.csv (project × country × condition) ---
# Compatible with your existing pipeline. Two-stage mode is optional.

# =========================
# Config: switches and filters
# =========================
#USE_TWO_STAGE         = True      # <-- set True to enable S1/S2 rows per project–country pair
#INCLUDE_SINGLE_PARTNER = False      # adds "single_partner" condition
#INCLUDE_BASELINE       = True      # adds one "baseline" row per project (no added partner)

USE_TWO_STAGE = True
INCLUDE_SINGLE_PARTNER = True    # keep this True, otherwise no Stage 2 runs will be made
INCLUDE_BASELINE = True

# Country inclusion controls (all optional)
UN_MEMBERS_ONLY      = False
ONLY_THESE_ISO3      = None        # e.g., {"GBR","USA","SAU"} or None
EXCLUDE_ISO3         = set()
ONLY_INCLUDE_BLOCS   = None        # e.g., {"EU","GCC"} or None
ONLY_INCLUDE_REGIONS = None        # e.g., {"Europe","Asia"} or None

# Reproducibility and output
SEED                 = 42
OUTPUT_PREFIX        = "runs_to_do"   # final file name is runs_to_do_*.csv
CHUNK_SIZE           = None           # e.g., 250_000 to write chunked CSVs, or None for single file

# Prompt variants and labels (optional)
PARTNER_TYPE         = "a public university"
TEMPLATE_VARIANT     = "v1"
TEMPLATE_JURIS_LABEL = "UK"           # appears in prompt header

# =========================
# Install & imports
# =========================
import sys, subprocess, hashlib, time, math
def pip_install(pkg):
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])

try:
    import pycountry
except ImportError:
    pip_install("pycountry")
    import pycountry

try:
    import pycountry_convert as pcc
    _HAS_PYCOUNTRY_CONVERT = True
except Exception:
    _HAS_PYCOUNTRY_CONVERT = False

import pandas as pd
import numpy as np
from google.colab import files

rng = np.random.default_rng(SEED)

# =========================
# Step 1: Upload projects.csv
# =========================
print("Please upload your projects.csv (columns: project_id,title,abstract,organisation,department,fixed_partners)")
uploaded = files.upload()

projects_csv = None
for k in uploaded.keys():
    if k.lower().endswith(".csv"):
        projects_csv = k
        break
if projects_csv is None:
    raise ValueError("No CSV detected. Please upload your projects.csv")

# =========================
# Step 2: Country table with bloc and region
# =========================
def build_countries_df():
    rows = []
    for c in pycountry.countries:
        iso3 = getattr(c, "alpha_3", None)
        name = c.name
        if not iso3:
            continue
        rows.append({"iso3": iso3, "country_name": name})
    df = pd.DataFrame(rows)

    # Simple UN-membership proxy (exclude Antarctica)
    un_like_exclusions = {"ATA"}
    df["is_un_member_like"] = ~df["iso3"].isin(un_like_exclusions)

    # Major blocs
    five_eyes = {"AUS","CAN","GBR","NZL","USA"}
    gcc       = {"BHR","KWT","OMN","QAT","SAU","ARE"}
    brics     = {"BRA","RUS","IND","CHN","ZAF"}  # classic BRICS-5
    eu = {
        "AUT","BEL","BGR","HRV","CYP","CZE","DNK","EST","FIN","FRA",
        "DEU","GRC","HUN","IRL","ITA","LVA","LTU","LUX","MLT","NLD",
        "POL","PRT","ROU","SVK","SVN","ESP","SWE"
    }

    def bloc_for(iso3):
        if iso3 in five_eyes: return "FiveEyes"
        if iso3 in gcc:       return "GCC"
        if iso3 in brics:     return "BRICS"
        if iso3 in eu:        return "EU"
        return "Other"

    df["bloc"] = df["iso3"].apply(bloc_for)

    if _HAS_PYCOUNTRY_CONVERT:
        code_to_region = {
            "AF": "Africa", "AS": "Asia", "EU": "Europe",
            "NA": "North America", "OC": "Oceania", "SA": "South America"
        }
        def region_for(iso3):
            try:
                iso2 = pcc.country_alpha3_to_country_alpha2(iso3)
                cc   = pcc.country_alpha2_to_continent_code(iso2)
                return code_to_region.get(cc, "Other")
            except Exception:
                return "Other"
        df["region"] = df["iso3"].apply(region_for)
    else:
        def region_for_fallback(iso3):
            if iso3 in {"GBR","FRA","DEU","ITA","ESP","SWE","NLD","POL","PRT","IRL","ROU","SVK","SVN","HRV","CZE","AUT","FIN","DNK","GRC","BGR","EST","LVA","LTU","LUX","MLT","CYP","BEL","HUN"}:
                return "Europe"
            if iso3 in {"USA","CAN","MEX"}:
                return "North America"
            if iso3 in {"AUS","NZL","PNG","FJI"}:
                return "Oceania"
            if iso3 in {"BRA","ARG","CHL","COL","PER","URY","PRY","VEN","BOL","ECU","SUR"}:
                return "South America"
            if iso3 in {"SAU","ARE","QAT","KWT","OMN","BHR","CHN","IND","JPN","KOR","IDN","IRN","ISR","TUR","PAK","PHL","MYS","SGP","THA","VNM"}:
                return "Asia"
            if iso3 in {"ZAF","NGA","EGY","ETH","KEN","GHA","DZA","MAR","TUN","UGA","TZA"}:
                return "Africa"
            return "Other"
        df["region"] = df["iso3"].apply(region_for_fallback)

    return df

countries = build_countries_df()

# Apply filters
if UN_MEMBERS_ONLY:
    countries = countries[countries["is_un_member_like"]].copy()
if ONLY_THESE_ISO3 is not None:
    countries = countries[countries["iso3"].isin(ONLY_THESE_ISO3)].copy()
if EXCLUDE_ISO3:
    countries = countries[~countries["iso3"].isin(EXCLUDE_ISO3)].copy()
if ONLY_INCLUDE_BLOCS is not None:
    countries = countries[countries["bloc"].isin(ONLY_INCLUDE_BLOCS)].copy()
if ONLY_INCLUDE_REGIONS is not None:
    countries = countries[countries["region"].isin(ONLY_INCLUDE_REGIONS)].copy()

# Stable ordering for reproducibility
countries = countries.sort_values(["bloc","region","iso3"]).reset_index(drop=True)

# =========================
# Step 3: Load projects and validate columns
# =========================
projects = pd.read_csv(projects_csv)
required_cols = {"project_id","title","abstract","organisation","department","fixed_partners"}
missing = required_cols - set(projects.columns)
if missing:
    raise ValueError(f"projects.csv is missing required columns: {sorted(missing)}")

# =========================
# Step 4: Helpers and templates
# =========================
def split_fixed_partners(fp_value):
    if isinstance(fp_value, float) and math.isnan(fp_value):
        return []
    if fp_value is None:
        return []
    txt = str(fp_value).strip()
    if not txt:
        return []
    return [p.strip() for p in txt.split(";") if p.strip()]

def est_token_len(s):
    return int(len(s) / 4)  # rough heuristic

def make_run_id(project_id, iso3, condition, template_variant, stage, prompt_text):
    h = hashlib.sha1()
    key = f"{project_id}|{iso3}|{condition}|{template_variant}|{stage}".encode("utf-8")
    h.update(key)
    h.update(prompt_text.encode("utf-8"))
    return h.hexdigest()

# Single-stage template (original)
PROMPT_TEMPLATE_SINGLE = (
    "You are assessing whether the following {juris_label} research project requires export control review.\n"
    "Return a single label: YES (controlled) or NO (not controlled), then a concise rationale referencing specific features.\n\n"
    "Title: {title}\n"
    "Abstract: {abstract}\n"
    "Organisation: {organisation}   Department: {department}\n"
    "Project Partners:\n"
    "{partners_block}\n\n"
    "Decision: YES/NO\n"
    "Rationale: (2-4 sentences)"
)

# Two-stage templates
# Stage 1: content-only
PROMPT_TEMPLATE_S1 = (
    "You are assessing whether the following {juris_label} research project requires export control review.\n"
    "Return a single label: YES (controlled) or NO (not controlled), then a concise rationale referencing specific technical features.\n"
    "Only consider the content, end use, and end user. Do not consider international partners.\n\n"
    "Title: {title}\n"
    "Abstract: {abstract}\n"
    "Organisation: {organisation}   Department: {department}\n"
    "Project Partners: (none)\n\n"
    "Decision: YES/NO\n"
    "Rationale: (2-4 sentences)"
)

# Stage 2: show prior S1 result placeholders and add partner
PROMPT_TEMPLATE_S2 = (
    "Previously you evaluated this project without international partners.\n\n"
    "Your prior decision: {s1_decision_hint}\n"
    "Your prior rationale: {s1_rationale_hint}\n\n"
    "Now consider this change: an additional project partner is {partner_type} located in {country_name}.\n"
    "Re-evaluate and return:\n"
    "1) Decision: YES or NO\n"
    "2) Rationale: 2-4 sentences explaining any change, citing relevant legal concepts for {juris_label}.\n\n"
    "Project (content unchanged):\n"
    "Title: {title}\n"
    "Abstract: {abstract}\n"
    "Organisation: {organisation}   Department: {department}"
)

def partners_block_for(condition, fixed_list, country_name, partner_type=PARTNER_TYPE):
    if condition == "baseline":
        lines = [f"- {p}" for p in fixed_list]
        return "\n".join(lines) if lines else "(none)"
    elif condition == "baseline_plus_one":
        lines = [f"- {p}" for p in fixed_list]
        lines.append(f"- Additional project partner: {partner_type} located in {country_name}.")
        return "\n".join(lines) if lines else f"- Additional project partner: {partner_type} located in {country_name}."
    elif condition == "single_partner":
        return f"- Additional project partner: {partner_type} located in {country_name}."
    else:
        raise ValueError("Unknown condition: " + condition)

# =========================
# Step 5: Generate rows
# =========================
# =========================
# Step 5: Generate rows  (S1 once per project, S2 per country)
# =========================
rows = []

# Make sure 'conditions' is defined earlier as exactly:
conditions = ["single_partner"]

for _, proj in projects.iterrows():
    fixed_list = split_fixed_partners(proj["fixed_partners"])
    baseline_count = len(fixed_list)

    if USE_TWO_STAGE:
        # --- Stage 1: once per project (content-only) ---
        prompt_s1 = PROMPT_TEMPLATE_S1.format(
            juris_label=TEMPLATE_JURIS_LABEL,
            title=proj["title"],
            abstract=proj["abstract"],
            organisation=proj["organisation"],
            department=proj["department"],
        )
        run_id_s1 = make_run_id(proj["project_id"], "---", "content_only", TEMPLATE_VARIANT, "S1", prompt_s1)
        rows.append({
            "run_id": run_id_s1,
            "template_version": TEMPLATE_VARIANT,
            "stage": "S1",
            "parent_run_id": "",
            "project_id": proj["project_id"],
            "iso3": "---",
            "country_name": "(none)",
            "condition": "content_only",
            "baseline_partner_count": baseline_count,
            "bloc": "(n/a)",
            "region": "(n/a)",
            "partner_type": PARTNER_TYPE,
            "prompt_text": prompt_s1,
            "prompt_hash": hashlib.sha1(prompt_s1.encode("utf-8")).hexdigest(),
            "prompt_len_chars": len(prompt_s1),
            "prompt_len_tokens_est": est_token_len(prompt_s1),
            "s1_decision_hint": "",
            "s1_rationale_hint": "",
        })

        # --- Stage 2: per country × condition (single_partner only) ---
        for _, cty in countries.iterrows():
            for cond in conditions:  # expected: ["single_partner"]
                prompt_s2 = PROMPT_TEMPLATE_S2.format(
                    juris_label=TEMPLATE_JURIS_LABEL,
                    title=proj["title"],
                    abstract=proj["abstract"],
                    organisation=proj["organisation"],
                    department=proj["department"],
                    country_name=cty["country_name"],
                    partner_type=PARTNER_TYPE,
                    s1_decision_hint="{FILL_AFTER_S1}",
                    s1_rationale_hint="{FILL_AFTER_S1}",
                )
                run_id_s2 = make_run_id(proj["project_id"], cty["iso3"], cond, TEMPLATE_VARIANT, "S2", prompt_s2)
                rows.append({
                    "run_id": run_id_s2,
                    "template_version": TEMPLATE_VARIANT,
                    "stage": "S2",
                    "parent_run_id": run_id_s1,
                    "project_id": proj["project_id"],
                    "iso3": cty["iso3"],
                    "country_name": cty["country_name"],
                    "condition": cond,
                    "baseline_partner_count": baseline_count,
                    "bloc": cty["bloc"],
                    "region": cty["region"],
                    "partner_type": PARTNER_TYPE,
                    "prompt_text": prompt_s2,
                    "prompt_hash": hashlib.sha1(prompt_s2.encode("utf-8")).hexdigest(),
                    "prompt_len_chars": len(prompt_s2),
                    "prompt_len_tokens_est": est_token_len(prompt_s2),
                    "s1_decision_hint": "",
                    "s1_rationale_hint": "",
                })

        # --- Optional single-stage baseline row per project (no partners) ---
        if INCLUDE_BASELINE:
            partners_block = partners_block_for("baseline", fixed_list, country_name="")
            prompt_base = PROMPT_TEMPLATE_SINGLE.format(
                juris_label=TEMPLATE_JURIS_LABEL,
                title=proj["title"],
                abstract=proj["abstract"],
                organisation=proj["organisation"],
                department=proj["department"],
                partners_block=partners_block,
            )
            run_id_base = make_run_id(proj["project_id"], "---", "baseline", TEMPLATE_VARIANT, "SINGLE", prompt_base)
            rows.append({
                "run_id": run_id_base,
                "template_version": TEMPLATE_VARIANT,
                "stage": "SINGLE",
                "parent_run_id": "",
                "project_id": proj["project_id"],
                "iso3": "---",
                "country_name": "(none)",
                "condition": "baseline",
                "baseline_partner_count": baseline_count,
                "bloc": "(n/a)",
                "region": "(n/a)",
                "partner_type": PARTNER_TYPE,
                "prompt_text": prompt_base,
                "prompt_hash": hashlib.sha1(prompt_base.encode("utf-8")).hexdigest(),
                "prompt_len_chars": len(prompt_base),
                "prompt_len_tokens_est": est_token_len(prompt_base),
                "s1_decision_hint": "",
                "s1_rationale_hint": "",
            })

    else:
        # --- Original single-stage behaviour (no two-stage protocol) ---
        for _, cty in countries.iterrows():
            for cond in conditions:  # expected: ["single_partner"]
                partners_block = partners_block_for(cond, fixed_list, cty["country_name"], partner_type=PARTNER_TYPE)
                prompt_text = PROMPT_TEMPLATE_SINGLE.format(
                    juris_label=TEMPLATE_JURIS_LABEL,
                    title=proj["title"],
                    abstract=proj["abstract"],
                    organisation=proj["organisation"],
                    department=proj["department"],
                    partners_block=partners_block,
                )
                run_id = make_run_id(proj["project_id"], cty["iso3"], cond, TEMPLATE_VARIANT, "SINGLE", prompt_text)
                rows.append({
                    "run_id": run_id,
                    "template_version": TEMPLATE_VARIANT,
                    "stage": "SINGLE",
                    "parent_run_id": "",
                    "project_id": proj["project_id"],
                    "iso3": cty["iso3"],
                    "country_name": cty["country_name"],
                    "condition": cond,
                    "baseline_partner_count": baseline_count,
                    "bloc": cty["bloc"],
                    "region": cty["region"],
                    "partner_type": PARTNER_TYPE,
                    "prompt_text": prompt_text,
                    "prompt_hash": hashlib.sha1(prompt_text.encode("utf-8")).hexdigest(),
                    "prompt_len_chars": len(prompt_text),
                    "prompt_len_tokens_est": est_token_len(prompt_text),
                    "s1_decision_hint": "",
                    "s1_rationale_hint": "",
                })

        if INCLUDE_BASELINE:
            partners_block = partners_block_for("baseline", fixed_list, country_name="")
            prompt_text = PROMPT_TEMPLATE_SINGLE.format(
                juris_label=TEMPLATE_JURIS_LABEL,
                title=proj["title"],
                abstract=proj["abstract"],
                organisation=proj["organisation"],
                department=proj["department"],
                partners_block=partners_block,
            )
            run_id = make_run_id(proj["project_id"], "---", "baseline", TEMPLATE_VARIANT, "SINGLE", prompt_text)
            rows.append({
                "run_id": run_id,
                "template_version": TEMPLATE_VARIANT,
                "stage": "SINGLE",
                "parent_run_id": "",
                "project_id": proj["project_id"],
                "iso3": "---",
                "country_name": "(none)",
                "condition": "baseline",
                "baseline_partner_count": baseline_count,
                "bloc": "(n/a)",
                "region": "(n/a)",
                "partner_type": PARTNER_TYPE,
                "prompt_text": prompt_text,
                "prompt_hash": hashlib.sha1(prompt_text.encode("utf-8")).hexdigest(),
                "prompt_len_chars": len(prompt_text),
                "prompt_len_tokens_est": est_token_len(prompt_text),
                "s1_decision_hint": "",
                "s1_rationale_hint": "",
            })

runs = pd.DataFrame(rows)

# Stable sort for reproducibility
sort_cols = ["project_id","condition","bloc","region","iso3","stage","run_id"]
sort_cols = [c for c in sort_cols if c in runs.columns]
runs = runs.sort_values(sort_cols).reset_index(drop=True)

# =========================
# Step 6: Save and sanity-check
# =========================
timestamp = time.strftime("%Y%m%d_%H%M%S")
out_csv = f"{OUTPUT_PREFIX}_{TEMPLATE_VARIANT}_{timestamp}.csv"

# After: conditions = ["single_partner"]
num_conditions = len(conditions)
conditions_label = " + ".join(conditions) if conditions else "(none)"
num_projects = projects.shape[0]
num_countries = countries.shape[0]

if USE_TWO_STAGE:
    # S1 once per project + S2 per country × condition (+ optional baseline)
    expected = (num_projects
                + num_projects * num_countries * num_conditions
                + (num_projects if INCLUDE_BASELINE else 0))
else:
    expected = (num_projects * num_countries * num_conditions
                + (num_projects if INCLUDE_BASELINE else 0))

print("---- SUMMARY ----")
print(f"Projects:  {num_projects}")
print(f"Countries: {num_countries}")
print(f"Conditions per project-country: {num_conditions} ({conditions_label})")
print(f"Include baseline rows: {INCLUDE_BASELINE}")
print(f"Two-stage mode: {USE_TWO_STAGE} (rows per pair: {'S1 once + S2 per country' if USE_TWO_STAGE else 'single-stage'})")
print(f"Expected rows: {expected}")
print(f"Actual rows:   {runs.shape[0]}")
print(f"Template version: {TEMPLATE_VARIANT} | Partner type: {PARTNER_TYPE} | Jurisdiction label: {TEMPLATE_JURIS_LABEL}")
print("-----------------")
print("Head:")
print(runs.head(3).to_string(index=False))

# Write CSV
if CHUNK_SIZE and runs.shape[0] > CHUNK_SIZE:
    total = runs.shape[0]
    n_chunks = (total + CHUNK_SIZE - 1) // CHUNK_SIZE
    for i in range(n_chunks):
        start = i * CHUNK_SIZE
        end = min((i + 1) * CHUNK_SIZE, total)
        chunk_name = f"{OUTPUT_PREFIX}_{TEMPLATE_VARIANT}_{timestamp}_part{i+1}_of_{n_chunks}.csv"
        runs.iloc[start:end].to_csv(chunk_name, index=False)
        print(f"Wrote chunk {i+1}/{n_chunks}: {chunk_name} [{start}:{end}]")
    files.download(chunk_name)  # last chunk
else:
    runs.to_csv(out_csv, index=False)
    files.download(out_csv)